steps:
	- name: gradle:jre11
	  entrypoint: gradle
	  args: ["test"]
	  dir: backend
	- name: gradle:jre11
	  entrypoint: gradle
	  args: ["assemble"]
	  dir: backend
	- name: gcr.io/cloud-builders/docker
	  args: ["build", "-t", "gcr.io/$PROJECT_ID/lokaler.kaufen", "--build-arg=JAR_FILE=backend/build/libs/mercury-0.0.1-SNAPSHOT.jar", "."]
  images: ["gcr.io/$PROJECT_ID/lokaler.kaufen"]