/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BreakDto } from './breakDto';

export interface BreaksDto { 
    friday?: Array<BreakDto>;
    monday?: Array<BreakDto>;
    saturday?: Array<BreakDto>;
    sunday?: Array<BreakDto>;
    thursday?: Array<BreakDto>;
    tuesday?: Array<BreakDto>;
    wednesday?: Array<BreakDto>;
}