/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {SlotConfigDto} from './slotConfigDto';

export interface ShopAdminDto {
    addressSupplement?: string;
    approved?: boolean;
    city?: string;
    contactTypes?: { [key: string]: string; };
    details?: string;
    email?: string;
    enabled?: boolean;
    id?: string;
    name?: string;
    ownerName?: string;
    slots?: SlotConfigDto;
    street?: string;
    website?: string;
    zipCode?: string;
}
export namespace ShopAdminDto {
    export type ContactTypesEnum = 'WHATSAPP' | 'PHONE' | 'FACETIME' | 'GOOGLE_DUO' | 'SKYPE' | 'SIGNAL' | 'VIBER';
    export const ContactTypesEnum = {
        WHATSAPP: 'WHATSAPP' as ContactTypesEnum,
        PHONE: 'PHONE' as ContactTypesEnum,
        FACETIME: 'FACETIME' as ContactTypesEnum,
        GOOGLEDUO: 'GOOGLE_DUO' as ContactTypesEnum,
        SKYPE: 'SKYPE' as ContactTypesEnum,
        SIGNAL: 'SIGNAL' as ContactTypesEnum,
        VIBER: 'VIBER' as ContactTypesEnum
    };
}
