/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {SlotConfigDto} from './slotConfigDto';

export interface ShopOwnerDetailDto {
    addressSupplement?: string;
    city?: string;
    contacts?: { [key: string]: string; };
    details?: string;
    id?: string;
    imageUrl?: string;
    name?: string;
    ownerName?: string;
    slots?: SlotConfigDto;
    street?: string;
    website?: string;
    zipCode?: string;
}
