/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {SocialLinksDto} from './socialLinksDto';

export interface ShopDetailDto {
  addressSupplement?: string;
  autoColorEnabled?: boolean;
  city?: string;
  contactTypes?: Array<string>;
  details?: string;
  email?: string;
  id?: string;
  imageUrl?: string;
  name?: string;
  ownerName?: string;
  shareLink?: string;
  shopColor?: string;
  socialLinks?: SocialLinksDto;
  street?: string;
  website?: string;
  zipCode?: string;
}
