## Login as admin

POST {{ host }}/api/admin/login
Content-Type: application/json
Accept: application/json, */*

{
    "email": "admin-1@local.host",
    "password": "admin-1"
}

### Login as user

POST {{ host }}/api/shop/login
Content-Type: application/json
Accept: application/json, */*

{
    "email": "moe@local.host",
    "password": "moe"
}

###