POST {{ host }}/api/shop/create?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmb29AYmFyLm9yZyIsImlzcyI6Im1lcmN1cnktc2hvcC1jcmVhdGlvbiJ9.WaUsDR89nzQtgqxXhfLZqazjf0PvywMzajQFZfKW9IQ
Accept: application/json, */*
Content-Type: application/json

{
    "id": "",
    "name": "Horst's Burgerladen",
    "ownerName": "Horst",
    "email": "info@example.com",
    "street": "Münchner Straße 13",
    "zipCode": "83464",
    "city": "München",
    "addressSupplement": "",
    "contactTypes": [
        "FACEBOOK_MESSENGER",
        "WHATSAPP"
    ]
}

### Send creation link

POST {{ host }}/api/shop/send-create-link
Accept: application/json
Content-Type: application/json

{
    "email": "foo@localhost"
}

###
