ALTER TABLE shop
    ALTER COLUMN created DROP DEFAULT;
ALTER TABLE shop
    ALTER COLUMN updated DROP DEFAULT;
ALTER TABLE shop
    ALTER COLUMN approved DROP DEFAULT;

ALTER TABLE reservation
    ALTER COLUMN created DROP DEFAULT;
ALTER TABLE reservation
    ALTER COLUMN updated DROP DEFAULT;
ALTER TABLE reservation
    ALTER COLUMN name DROP DEFAULT;

ALTER TABLE shop_login
    ALTER COLUMN created DROP DEFAULT;
ALTER TABLE shop_login
    ALTER COLUMN updated DROP DEFAULT;

ALTER TABLE admin
    ALTER COLUMN created DROP DEFAULT;
ALTER TABLE admin
    ALTER COLUMN updated DROP DEFAULT;