package de.qaware.mercury.test.builder;

import de.qaware.mercury.business.shop.DayConfig;
import de.qaware.mercury.business.shop.SlotConfig;

/**
 * Generated by IntelliJ.
 */
public class SlotConfigBuilder {
    private int timePerSlot;
    private int timeBetweenSlots;
    private int delayForFirstSlot;
    private DayConfig monday;
    private DayConfig tuesday;
    private DayConfig wednesday;
    private DayConfig thursday;
    private DayConfig friday;
    private DayConfig saturday;
    private DayConfig sunday;

    public SlotConfigBuilder setTimePerSlot(int timePerSlot) {
        this.timePerSlot = timePerSlot;
        return this;
    }

    public SlotConfigBuilder setTimeBetweenSlots(int timeBetweenSlots) {
        this.timeBetweenSlots = timeBetweenSlots;
        return this;
    }

    public SlotConfigBuilder setDelayForFirstSlot(int delayForFirstSlot) {
        this.delayForFirstSlot = delayForFirstSlot;
        return this;
    }

    public SlotConfigBuilder setMonday(DayConfig monday) {
        this.monday = monday;
        return this;
    }

    public SlotConfigBuilder setTuesday(DayConfig tuesday) {
        this.tuesday = tuesday;
        return this;
    }

    public SlotConfigBuilder setWednesday(DayConfig wednesday) {
        this.wednesday = wednesday;
        return this;
    }

    public SlotConfigBuilder setThursday(DayConfig thursday) {
        this.thursday = thursday;
        return this;
    }

    public SlotConfigBuilder setFriday(DayConfig friday) {
        this.friday = friday;
        return this;
    }

    public SlotConfigBuilder setSaturday(DayConfig saturday) {
        this.saturday = saturday;
        return this;
    }

    public SlotConfigBuilder setSunday(DayConfig sunday) {
        this.sunday = sunday;
        return this;
    }

    public SlotConfig build() {
        return new SlotConfig(timePerSlot, timeBetweenSlots, delayForFirstSlot, monday, tuesday, wednesday, thursday, friday, saturday, sunday);
    }
}