package de.qaware.mercury.business.random;

/**
 * Generates random numbers.
 */
public interface RNG {
    /**
     * Generates the given number of random bytes.
     * <p>
     * If you need crypto-safe random data, use {@link #nextBytesSecure(int)}.
     *
     * @param size number of random bytes to generate
     * @return random bytes
     */
    byte[] nextBytes(int size);

    /**
     * Generates the given number of random bytes. The generated bytes are safe for crypto use.
     *
     * @param size number of random bytes to generate
     * @return random bytes
     */
    byte[] nextBytesSecure(int size);
}
